---
version: 2
jobs:
  # This plugin requires a custom image to test releases.
  # Currently it's using Node v10.
  node-12: &test
    docker:
      - image: circleci/node:erbium
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v3-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v3-yarn-{{checksum ".circleci/config.yml"}}
      - run: yarn
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --frozen-lockfile
      - run: |
          yarn semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v3-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/plugin-update":
    jobs:
      - node-12
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-12
